; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "DNACloud"
#define MyAppVersion "1.0"
#define MyAppPublisher "Gupta Lab"
#define MyAppURL "www.guptalab.org/dnacloud"
#define MyAppExeName "DNACloud.exe"
#define RegistryScript "register.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{96D30ADB-BC69-47D1-8E91-52909F54F9AE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName="C:\DNA-Cloud"
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=D:\DNA-Cloud\LICENCE.rtf
InfoBeforeFile=D:\DNA-Cloud\README.rtf
OutputDir=C:\Users\Shalin-Vaio\Desktop
OutputBaseFilename=dna_cloud_windows
SetupIconFile=D:\DNA-Cloud\icons\DNAicon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "D:\DNA-Cloud\source\DNACloud.exe"; DestDir: "{app}\source"; Flags: ignoreversion
Source: "D:\DNA-Cloud\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\source\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppURL}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\source\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\source\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]

Filename: "{app}\{#RegistryScript}";
Filename: "{app}\source\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

